name: greening

on:
  push:
    branches:
      - master

  schedule:
    - cron: "0 1/4 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --local user.email "mohammadsahrullah894@gmail.com"
          git config --local user.name "sahrullahh"
          git add -A

          arr[0]="chore(bot): greening up"
          arr[1]="chore(bot): go green"
          arr[2]="chore(bot): trees"
          arr[3]="chore(bot): climate changes"
          arr[4]="chore(bot): hey you what are you doing?"
          arr[5]="chore(bot): make it green"
          arr[6]="chore(bot): doing it myself" 
          arr[7]="chore(bot): for green"
          arr[8]="chore(bot): I like green"
          arr[9]="chore(bot): make it green"

          rand=$[$RANDOM % ${#arr[@]}]

          git commit -m "${arr[$rand]}"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
